name: Validate Renovate configuration

on:
  pull_request:
    paths:
      # Run on any renovate.json5, not just .github/renovate.json5
      - '**renovate.json5'

jobs:
  validate:
    name: Validate Renovate configuration
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout configuration
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # this step uses latest renovate slim release
      - name: Validate configuration
        run: |
          # renovate: datasource=docker
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:43.46.2@sha256:9065b369b9697b7898ef653edd492b1495a3ba0fdf941da78ef015400c6f9b3e
          docker run --rm --entrypoint "renovate-config-validator" \
            -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5" \
            ${RENOVATE_IMAGE} "/renovate.json5"
